### ISSUE TITLE
Image flickers within any tab on first visit

### ISSUE THREAD

**Issue by Tes3awy** [karambafe/vue-tabs-with-active-line#9]
First, let me thank you for this awesome plugin. I am using the plugin to create a timeline. It works great but I have a problem. Each tab contains an image and some text. when I click any title to go to that tab, the image flickers. However; if I visit the same tab again it doesn't flicker. You can find this issue on this [page](https://pc-frontend.staging.34ml.com/about) in the **Our Story** section only on mobile devices. So please open the browser emulator to see it. I'd appreciate any help. Thank you

**Comment by karambafe** [comment]
Hi!
I think this problem is not related to the plugin.

At the first call the browser asynchronously downloads the image, so there is such a flicker. On subsequent transitions, the picture is taken from the cache, so there is no flicker.

Set the minimum height for the parent container of the image so that at the time of loading there are no content twitches.

**Comment by Tes3awy** [comment]
@karambafe Thanks a lot for the tip. Works like a charm :+1:
